Upstream Trusted Types integration with SVGAnimatedString
w3c/svgwg pull request #934
Opened 2024-03-20 14:05 UTC by lukewarlow

This PR upstreams the trusted types integration with SVGAnimatedString. See https://w3c.github.io/trusted-types/dist/spec/#integration-with-svg

2024-03-20 14:27 UTC, caribouW3 commented
It would be good to have a publish version of the trusted types spec instead of an editor's draft.

2024-03-20 14:28 UTC, caribouW3 requested changes
Please refer to a /TR version rather than an editor's  draft.

2024-03-20 14:56 UTC, caribouW3 approved these changes

2024-03-20 14:56 UTC, caribouW3 approved these changes

2024-03-20 14:57 UTC, merged

2024-04-03 16:15 UTC, lukewarlow commented
@caribouW3 this doesn't appear to be updated in https://svgwg.org/svg2-draft/types.html#InterfaceSVGAnimatedString

Does this just need publishing or have I missed something in this PR that I need to change?